begin;

insert into public.ebook_catalog (id, title, price, status) values
  ('1', 'Mindful Living Guide', 20, 'available'),
  ('2', 'Stress Management', 20, 'available'),
  ('3', 'Advanced Meditation Techniques', 21, 'available'),
  ('4', 'Mind-Body Connection', 20, 'available'),
  ('5', 'Holistic Health & Wellness', 21, 'available'),
  ('6', 'Physical Training Fundamentals', 24, 'available'),
  ('7', 'Elite Performance Training', 42, 'available'),
  ('8', 'Nutrition Basics', 18, 'available'),
  ('9', 'Advanced Nutrition Science', 40, 'available'),
  ('10', 'Cognitive Enhancement', 38, 'available'),
  ('11', 'Mastering Focus & Concentration', 40, 'available'),
  ('12', 'Elite Mental Performance', 44, 'available'),
  ('13', 'Memory Mastery', 42, 'available'),
  ('14', 'Daily Habits for Success', 18, 'available'),
  ('15', 'Time Management Mastery', 20, 'available'),
  ('16', 'Leadership & Influence', 42, 'available'),
  ('17', 'Goal Setting & Achievement', 38, 'available'),
  ('18', 'Quantum Physics Basics', 44, 'available'),
  ('19', 'Artificial Intelligence Fundamentals', 42, 'available'),
  ('20', 'Blockchain & Cryptocurrency', 40, 'available'),
  ('21', 'Programming Fundamentals', 38, 'available'),
  ('22', 'Data Science Essentials', 40, 'available'),
  ('23', 'World History Essentials', 18, 'available'),
  ('24', 'Philosophy for Modern Life', 42, 'available'),
  ('25', 'Economics Fundamentals', 38, 'available'),
  ('26', 'Psychology Basics', 40, 'available'),
  ('27', 'Entrepreneurship Guide', 44, 'available'),
  ('28', 'Personal Finance Mastery', 38, 'available'),
  ('29', 'Investment Strategies', 46, 'available'),
  ('30', 'Creative Thinking', 36, 'available'),
  ('31', 'Digital Art Fundamentals', 38, 'available'),
  ('32', 'Writing Mastery', 38, 'available'),
  ('33', 'Relationship Psychology', 38, 'available'),
  ('34', 'Parenting Essentials', 40, 'available'),
  ('35', 'Minimalism & Decluttering', 18, 'available'),
  ('36', 'Spiritual Growth', 40, 'available'),
  ('37', 'Eastern Philosophy', 40, 'available'),
  ('38', 'Mindfulness in Daily Life', 20, 'available'),
  ('39', 'Neuroscience of Learning', 48, 'available'),
  ('40', 'Quantum Consciousness', 46, 'available'),
  ('41', 'Biohacking Fundamentals', 44, 'available'),
  ('42', 'Future Technologies', 42, 'available'),
  ('43', 'Elite Performance Mastery', 52, 'available'),
  ('44', 'Advanced Cognitive Enhancement', 54, 'available'),
  ('45', 'Creative Genius Unleashed', 50, 'available'),
  ('46', 'Wealth Building Mastery', 52, 'available'),
  ('47', 'Life Transformation Blueprint', 50, 'available')
on conflict (id) do update set
  title = excluded.title,
  price = excluded.price,
  status = excluded.status;

commit;
