export const CATEGORY_COPY: Record<string, { title: string; subtitle: string; back: string }> = {
  attention: { title: 'Attention', subtitle: 'Easy is open. Medium at level 2, hard at level 5.', back: '/MentalTrainingScreen' },
  memory: { title: 'Memory', subtitle: 'Start with a short recall. Longer sets unlock by level.', back: '/MentalTrainingScreen' },
  logic: { title: 'Logic', subtitle: 'Reasoning starts simple and opens up with levels.', back: '/MentalTrainingScreen' },
  speed: { title: 'Speed', subtitle: 'Reaction is open. Harder patterns wait for higher levels.', back: '/MentalTrainingScreen' },
  verbal: { title: 'Verbal', subtitle: 'A short word exercise to begin.', back: '/MentalTrainingScreen' },
  visual: { title: 'Visual', subtitle: 'A short visual match to begin.', back: '/MentalTrainingScreen' },
  creativity: { title: 'Creativity', subtitle: 'A short prompt to begin.', back: '/MentalTrainingScreen' },
  critical: { title: 'Critical thinking', subtitle: 'These sets open once you level up.', back: '/MentalTrainingScreen' },
  meta: { title: 'Metacognition', subtitle: 'Reflection is open. Deeper reviews unlock by level.', back: '/MentalTrainingScreen' },
  flexibility: { title: 'Flexibility', subtitle: 'This path is being prepared.', back: '/MentalTrainingScreen' },
  executive: { title: 'Executive', subtitle: 'This path is being prepared.', back: '/MentalTrainingScreen' },
  breathing: { title: 'Breathing', subtitle: 'Start with box breathing. Stronger sets unlock by level.', back: '/PhysicalTrainingScreen' },
  stretching: { title: 'Stretching', subtitle: 'Gentle stretches are open first.', back: '/PhysicalTrainingScreen' },
  balance: { title: 'Balance', subtitle: 'Start with a still stand.', back: '/PhysicalTrainingScreen' },
  strength: { title: 'Strength', subtitle: 'A short plank is open. The circuit unlocks later.', back: '/PhysicalTrainingScreen' },
  relaxation: { title: 'Relaxation', subtitle: 'Begin with a body scan.', back: '/PhysicalTrainingScreen' },
  mobility: { title: 'Mobility', subtitle: 'Move each joint through a comfortable range.', back: '/PhysicalTrainingScreen' },
  endurance: { title: 'Endurance', subtitle: 'Start with an easy interval.', back: '/PhysicalTrainingScreen' },
  coordination: { title: 'Coordination', subtitle: 'Start with a simple cross-crawl.', back: '/PhysicalTrainingScreen' },
  posture: { title: 'Posture', subtitle: 'This path is being prepared.', back: '/PhysicalTrainingScreen' },
};
